serverAddr = "127.0.0.1"
serverPort = 7000

# Логирование
log.level = "info"
log.maxDays = 3

# Проксирование HTTP (порт 80 -> 4080)
[[proxies]]
name = "web-http"
type = "tcp"
localIP = "127.0.0.1"
localPort = 80
remotePort = 4080

# Проксирование HTTPS (порт 443 -> 4443)
[[proxies]]
name = "web-https"
type = "tcp"
localIP = "127.0.0.1"
localPort = 443
remotePort = 4443
