bindAddr = "0.0.0.0"
bindPort = 7000
bindUDPPort = 7000

# Веб-интерфейс
webServer.addr = "127.0.0.1"
webServer.port = 7500
webServer.user = "admin"
webServer.password = "admin"

# Логирование
log.level = "info"
log.maxDays = 3
